apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-report-webhook-api
  labels:
    app: sensors-report-webhook-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensors-report-webhook-api
  template:
    metadata:
      labels:
        app: sensors-report-webhook-api
    spec:
      containers:
        - name: sensors-report-webhook-api
          image: viobiscu/sensors-report-webhook-api:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: SR_OrionLdOptions__BrokerUrl
              value: "http://orion-ld-broker:1026"
            - name: SR_EventBusOptions__Host
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-default-user
                  key: host
            - name: SR_EventBusOptions__Port
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-default-user
                  key: port
            - name: SR_EventBusOptions__Username
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-default-user
                  key: username
            - name: SR_EventBusOptions__Password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-default-user
                  key: password