apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-report-notificationrule-api
  labels:
    app: sensors-report-notificationrule-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensors-report-notificationrule-api
  template:
    metadata:
      labels:
        app: sensors-report-notificationrule-api
    spec:
      containers:
        - name: sensors-report-notificationrule-api
          image: viobiscu/sensors-report-notificationrule-api:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: SR_OrionLdConfig__BrokerUrl
              value: "http://orion-ld-broker:1026"
