apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-report-email-api
  labels:
    app: sensors-report-email-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensors-report-email-api
  template:
    metadata:
      labels:
        app: sensors-report-email-api
    spec:
      containers:
      - name: sensors-report-email-api
        image: viobiscu/sensors-report-email-api:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: SR_EmailMongoDbConnectionOptions__ConnectionString
          valueFrom:
            secretKeyRef:
              name: notification-api-mongodb-connection
              key: MONGODB_URI
        - name: SR_EmailMongoDbConnectionOptions__DatabaseName
          value: email-db
        - name: SR_EmailMongoDbConnectionOptions__CollectionName
          value: email
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: SR_EventBusOptions__Host
          valueFrom:
            secretKeyRef:
              name: rabbitmq-default-default-user
              key: host
        - name: SR_EventBusOptions__Port
          valueFrom:
            secretKeyRef:
              name: rabbitmq-default-default-user
              key: port
        - name: SR_EventBusOptions__Username
          valueFrom:
            secretKeyRef:
              name: rabbitmq-default-default-user
              key: username
        - name: SR_EventBusOptions__Password
            valueFrom:
                secretKeyRef:
                name: rabbitmq-default-default-user
                key: password
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
