apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-report-email-api
  labels:
    app: sensors-report-email-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensors-report-email-api
  template:
    metadata:
      labels:
        app: sensors-report-email-api
    spec:
      containers:
      - name: sensors-report-email-api
        image: sensors-report-email-api:dev
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: Keycloak__Authority
          value: http://keycloak:8080/realms/sr
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
