# Dockerfile for Sensors-Report-Explorer frontend (Nginx)
FROM nginx:alpine

# Copy static files
COPY . /usr/share/nginx/html

# Copy entrypoint script
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]
