apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-report-sms-api
  labels:
    app: sensors-report-sms-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensors-report-sms-api
  template:
    metadata:
      labels:
        app: sensors-report-sms-api
    spec:
      containers:
      - name: sensors-report-sms-api
        image: viobiscu/sensors-report-sms-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: SR_SmsMongoDbConnectionOptions__ConnectionString
          valueFrom:
            secretKeyRef:
              name: notification-api-mongodb-connection
              key: MONGODB_URI
        - name: SR_SmsMongoDbConnectionOptions__DatabaseName
          value: sms-db
        - name: SR_SmsMongoDbConnectionOptions__CollectionName
          value: sms
        - name: SR_ProviderMongoDbConnectionOptions__ConnectionString
          valueFrom:
            secretKeyRef:
              name: notification-api-mongodb-connection
              key: MONGODB_URI
        - name: SR_ProviderMongoDbConnectionOptions__DatabaseName
          value: sms-db
        - name: SR_ProviderMongoDbConnectionOptions__CollectionName
          value: providers
        - name: SR_SmsOptions__ProviderTrustTimeoutInSecond
          value: "1800"  # 30 minutes
        - name: SR_SmsOptions__MaxRetryCount
          value: "3"
        - name: SR_SmsOptions__DefaultTtlInMinutes
          value: "30"  # Default TTL for SMS messages
        - name: SR_EventBusOptions__Host
          valueFrom:
            secretKeyRef:
              name: rabbitmq-default-default-user
              key: host
        - name: SR_EventBusOptions__Port
          valueFrom:
            secretKeyRef:
              name: rabbitmq-default-default-user
              key: port
        - name: SR_EventBusOptions__Username
          valueFrom:
            secretKeyRef:
              name: rabbitmq-default-default-user
              key: username
        - name: SR_EventBusOptions__Password
            valueFrom:
                secretKeyRef:
                name: rabbitmq-default-default-user
                key: password
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
