apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-report-business-broker-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensors-report-business-broker-api
  template:
    metadata:
      labels:
        app: sensors-report-business-broker-api
    spec:
      containers:
        - name: sensors-report-business-broker-api
          image: viobiscu/sensors-report-business-broker-api:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
