---
apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: default
type: Opaque
stringData:
  SA_PASSWORD: "kqI0@pKBLQl9PFSbRN"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-mssql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-mssql
  template:
    metadata:
      labels:
        app: frontend-mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_PASSWORD
          volumeMounts:
            - name: mssql-storage
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-storage
          persistentVolumeClaim:
            claimName: mssql-data

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-mssql-svc
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 1433
      targetPort: 1433
  selector:
    app: frontend-mssql

---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-api-mssql-connection
  namespace: default
type: Opaque
stringData:
  MSSQL_URI: "Server=frontend-mssql-svc.default.svc.cluster.local,1433;Database=frontenddb;User ID=sa;Password=kqI0@pKBLQl9PFSbRN;TrustServerCertificate=True;"
