apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-report-provisioning-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensors-report-provisioning-api
  template:
    metadata:
      labels:
        app: sensors-report-provisioning-api
    spec:
      containers:
      - name: sensors-report-provisioning-api
        image: viobiscu/sensors-report-provision-api:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: OrionContextBrokerUrl
            value: "http://orion-ld-broker:1026"
