apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-report-email-consumer
  labels:
    app: sensors-report-email-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensors-report-email-consumer
  template:
    metadata:
      labels:
        app: sensors-report-email-consumer
    spec:
      containers:
      - name: sensors-report-email-consumer
        image: viobiscu/sensors-report-email-consumer:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "96Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: SR_EmailMongoDbConnectionOptions__ConnectionString
          valueFrom:
            secretKeyRef:
              name: notification-api-mongodb-connection
              key: MONGODB_URI
        - name: SR_EmailMongoDbConnectionOptions__DatabaseName
          value: email-db
        - name: SR_EmailMongoDbConnectionOptions__CollectionName
          value: email
        envFrom:
        - secretRef:
            name: rabbitmq-default-default-user
            prefix: "SR_EventBusOptions__"
        - secretRef:
            name: email-smtp-secret
            prefix: "SR_SmtpOptions__"
      volumes:
      - name: logs
        emptyDir: {}
