apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-report-audit-api-v1
  labels:
    app: sensors-report-audit-api-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensors-report-audit-api-v1
  template:
    metadata:
      labels:
        app: sensors-report-audit-api-v1
    spec:
      containers:
        - name: sensors-report-audit-api-v1
          image: viobiscu/sensors-report-audit-api:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: SR_AUDIT_QUANTUMLEAP_HOST
              value: "quantum.sensorsreport.net"
            - name: SR_AUDIT_QUANTUMLEAP_PORT
              value: "8668"
 
 
 
 
 
 
 
 
