

@quantumleap = http://162.244.27.122:8668

### Health Check
GET {{quantumleap}}/health
#Authorization: Bearer {{access_token}}

### Version
GET {{quantumleap}}/version

### Entities
GET {{quantumleap}}/v2/entities

### Subscriptions
POST {{quantumleap}}/v2/subscriptions/ HTTP/1.1
Content-Type: application/json
NGSILD-Tenant: openiot
NGSILD-Path: /