apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sensors-report-explorer-backend
  name: sensors-report-explorer-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensors-report-explorer-backend
  template:
    metadata:
      annotations:
        backend-image-version: '105'
      labels:
        app: sensors-report-explorer-backend
    spec:
      containers:
      - env:
        - name: FLASK_ENV
          value: development
        - name: FLASK_RUN_HOST
          value: 0.0.0.0
        - name: LOG_LEVEL
          value: DEBUG
        - name: SECRET_KEY
          value: prod-secret-key
        - name: CORS_ORIGINS
          value: '*'
        - name: KEYCLOAK_AUTH_URL
          value: https://keycloak.sensorsreport.net/realms/sr/protocol/openid-connect/auth
        - name: KEYCLOAK_TOKEN_URL
          value: https://keycloak.sensorsreport.net/realms/sr/protocol/openid-connect/token
        - name: KEYCLOAK_USERINFO_URL
          value: https://keycloak.sensorsreport.net/realms/sr/protocol/openid-connect/userinfo
        - name: KEYCLOAK_LOGOUT_URL
          value: https://keycloak.sensorsreport.net/realms/sr/protocol/openid-connect/logout
        - name: KEYCLOAK_CLIENT_ID
          value: ContextBroker
        - name: KEYCLOAK_CLIENT_SECRET
          value: ''
        - name: QUANTUM_LEAP_URL
          value: http://162.244.27.122:8668
        - name: DATA_PRODUCT_URL
          value: http://data-product-manager:8000
        - name: CONTEXT_BROKER_URL
          value: http://orion-ld-broker:1026
        - name: SECURE_COOKIES
          value: 'false'
        - name: HOST
          value: 0.0.0.0
        - name: PORT
          value: '5000'
        - name: DEBUG
          value: 'true'
        - name: REDIRECT_URI
          value: https://explorer.sensorsreport.net/api/auth/callback
        image: viobiscu/sensors-report-explorer-backend:105
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - 'if command -v apt-get >/dev/null 2>&1; then apt-get update && apt-get
                install -y iputils-ping curl; fi

                if command -v apk >/dev/null 2>&1; then apk add --no-cache iputils
                curl; fi

                '
        name: sensors-report-explorer-backend
        ports:
        - containerPort: 5000
