apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-report-explorer
  labels:
    app: sensors-report-explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensors-report-explorer
  template:
    metadata:
      labels:
        app: sensors-report-explorer
    spec:
      containers:
        - name: sensors-report-explorer
          image: viobiscu/sensors-report-explorer:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
            - name: FLASK_RUN_HOST
              value: "0.0.0.0"
            - name: LOG_LEVEL
              value: "INFO"
            - name: SECRET_KEY
              value: "prod-secret-key"
            - name: CORS_ORIGINS
              value: "*"
            - name: KEYCLOAK_AUTH_URL
              value: "http://keycloak.sensorsreport.net/realms/sr/protocol/openid-connect/auth"
            - name: KEYCLOAK_TOKEN_URL
              value: "http://keycloak.sensorsreport.net/realms/sr/protocol/openid-connect/token"
            - name: KEYCLOAK_USERINFO_URL
              value: "http://keycloak.sensorsreport.net/realms/sr/protocol/openid-connect/userinfo"
            - name: KEYCLOAK_LOGOUT_URL
              value: "http://keycloak.sensorsreport.net/realms/sr/protocol/openid-connect/logout"
            - name: KEYCLOAK_CLIENT_ID
              value: "ContextBroker"
            - name: KEYCLOAK_CLIENT_SECRET
              value: ""
            - name: QUANTUM_LEAP_URL
              value: "http://quantumleap:8668"
            - name: DATA_PRODUCT_URL
              value: "http://data-product-manager:8000"
            - name: CONTEXT_BROKER_URL
              value: "http://orion-ld-broker:1026"
            - name: SECURE_COOKIES
              value: "true"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "5000"
            - name: DEBUG
              value: "false"
            - name: REDIRECT_URI
              value: "http://explorer.sensorsreport.net/api/auth/callback"
