apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-report-explorer-frontend
  labels:
    app: sensors-report-explorer-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensors-report-explorer-frontend
  template:
    metadata:
      labels:
        app: sensors-report-explorer-frontend
    spec:
      containers:
        - name: sensors-report-explorer-frontend
          image: viobiscu/sensors-report-explorer-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_BASE_URL
              value: "http://sensors-report-explorer-backend:5000"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: sensors-report-explorer-nginx-config
