apiVersion: v1
kind: Service
metadata:
  name: sensors-report-explorer
spec:
  selector:
    app: sensors-report-explorer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
