apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-report-mqtt-to-orion
  labels:
    app: sensors-report-mqtt-to-orion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sensors-report-mqtt-to-orion
  template:
    metadata:
      labels:
        app: sensors-report-mqtt-to-orion
    spec:
      containers:
        - name: sensors-report-mqtt-to-orion
          image: viobiscu/sensors-report-mqtt-to-orion:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            # Add other production environment variables here
