apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-report-mqtt-to-orion-test
  labels:
    app: sensors-report-mqtt-to-orion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensors-report-mqtt-to-orion
  template:
    metadata:
      labels:
        app: sensors-report-mqtt-to-orion
    spec:
      containers:
        - name: sensors-report-mqtt-to-orion
          image: viobiscu/srmqtt-orion:dev
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            # Add other dev/test environment variables here
