apiVersion: v1
kind: Service
metadata:
  name: sensors-report-mqtt-to-orion
spec:
  selector:
    app: sensors-report-mqtt-to-orion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
