apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-report-email-consumer
  labels:
    app: sensors-report-email-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensors-report-email-consumer
  template:
    metadata:
      labels:
        app: sensors-report-email-consumer
    spec:
      containers:
      - name: sensors-report-email-consumer
        image: viobiscu/sensors-report-email-consumer:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "96Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: SR_EmailMongoDbConnectionOptions__ConnectionString
          valueFrom:
            secretKeyRef:
              name: notification-api-mongodb-connection
              key: MONGODB_URI
        - name: SR_EmailMongoDbConnectionOptions__DatabaseName
          value: email-db
        - name: SR_EmailMongoDbConnectionOptions__CollectionName
          value: email
        - name: SR_EventBusOptions__Host
          valueFrom:
            secretKeyRef:
              name: rabbitmq-default-default-user
              key: host
        - name: SR_EventBusOptions__Port
          valueFrom:
            secretKeyRef:
              name: rabbitmq-default-default-user
              key: port
        - name: SR_EventBusOptions__Username
          valueFrom:
            secretKeyRef:
              name: rabbitmq-default-default-user
              key: username
        - name: SR_EventBusOptions__Password
          valueFrom:
            secretKeyRef:
              name: rabbitmq-default-default-user
              key: password
        - name: SR_SmtpOptions__Server
          valueFrom:
            secretKeyRef:
              name: email-smtp-secret
              key: Server
        - name: SR_SmtpOptions__Port
          valueFrom:
            secretKeyRef:
              name: email-smtp-secret
              key: Port
        - name: SR_SmtpOptions__Username
          valueFrom:
            secretKeyRef:
              name: email-smtp-secret
              key: Username
        - name: SR_SmtpOptions__Password
          valueFrom:
            secretKeyRef:
              name: email-smtp-secret
              key: Password
        - name: SR_SmtpOptions__UseSSL
          valueFrom:
            secretKeyRef:
              name: email-smtp-secret
              key: UseSSL
      volumes:
      - name: logs
        emptyDir: {}
