apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-report-alarmrule-consumer
  labels:
    app: sensors-report-alarmrule-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensors-report-alarmrule-consumer
  template:
    metadata:
      labels:
        app: sensors-report-alarmrule-consumer
    spec:
      containers:
      - name: sensors-report-alarmrule-consumer
        image: viobiscu/sensors-report-alarmrule-consumer:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "96Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: SR_RabbitMQQueueConfig__RabbitMQConnectionString
          valueFrom:
            secretKeyRef:
              name: rabbitmq-default-default-user
              key: connection_string
        - name: SR_RabbitMQQueueConfig__RabbitMQExchange
          value: sensorsreport.exchange.notification.webhook
        - name: SR_RRabbitMQQueueConfig__RabbitMQQueue
          value: sensorsreport.exchange.notification.alarmrule
        - name: SR_RabbitMQQueueConfig__RabbitMQRoutingKey
          value: sensorsreport.exchange.notification.alarmrule
        - name: SR_OrionLdConfig__OrionContextBrokerUrl
          value: "http://orion-ld-broker:1026"
      volumes:
      - name: logs
        emptyDir: {}
