apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sensors-report
  namespace: flux-system
spec:
  interval: 1m
  path: ./flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: sensors-report
