apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sensors-report-audit
  namespace: flux-system
spec:
  interval: 1m
  url: file:///home/vio/Documents/SensorsReport
  ref:
    branch: main