apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sensors-report
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/viobiscu/SensorsReport
  ref:
    branch: main
